version: '3.8'

services:
  mem8-explorer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    labels:
      # Coolify specific labels
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=mem8-explorer"
      - "coolify.description=80s retro wave-based memory visualization"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s